-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 00:49:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-projet` DEFAULT CHARACTER SET utf8 ;
USE `db-projet` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-projet`.`user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `forename` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(125) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-projet`.`role` (
  `id_role` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-projet`.`user_has_role` (
  `user_id_user` INT NOT NULL,
  `role_id_role` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `role_id_role`),
  INDEX `fk_user_has_role_role1_idx` (`role_id_role` ASC) VISIBLE,
  INDEX `fk_user_has_role_user_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id_role`)
    REFERENCES `mydb`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rdv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-projet`.`rdv` (
  `id_rdv` INT NOT NULL,
  `date_rdv` DATETIME NULL,
  `user_id_user` INT NOT NULL,
  `user_has_role_doc_id_user` INT NOT NULL COMMENT 'doit être un médécin',
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rdv`, `user_id_user`, `user_has_role_doc_id_user`),
  INDEX `fk_rdv_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_rdv_user2_idx` (`user_has_role_doc_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_rdv_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rdv_user2`
    FOREIGN KEY (`user_has_role_doc_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
